site_name: Valmere 
repo_url: https://gitlab.com/midnightprioriem/valmere-wiki
use_directory_urls: True 
markdown_extensions:
        - smarty
        - admonition
        - mdx_truly_sane_lists
        - attr_list
        - extra
extra_css:
        - css/theme.css
        - css/codehilite.css
        - css/sidebar.css
extra_javascript:
        - js/jquery-3.4.1.js
        
theme: 
        name: material
        custom_dir: 'theme'
        logo: 
                icon: 'public'
plugins:
        - search
        - macros
        - autolinks
        - nav-extra 

nav:
