site_name: Valmere 
repo_url: https://gitlab.com/midnightprioriem/valmere-wiki
use_directory_urls: True 
markdown_extensions:
        - smarty
        - admonition
        - mdx_truly_sane_lists
        - attr_list
        - extra
extra_css:
        - css/theme.css
        - css/codehilite.css
        - css/sidebar.css
        - css/link-tooltips.css
        - css/tooltipster.bundle.min.css
        - css/tooltipster-sideTip-shadow.min.css
extra_javascript:
        - js/tooltipster.bundle.js 
theme: 
        name: material
        custom_dir: 'theme'
        logo: 
                icon: 'public'
plugins:
        - search
        - macros
        - autolinks
        - toc-sidebar
        - tooltipster-links 
        - vim-md-tags 

nav:
